### ISSUE TITLE
Change text colour for name field

### ISSUE THREAD

**Issue by staljabro** [wrodie/mixer-card#3]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/wrodie/mixer-card/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'm wanting the ability to change colour. My HA instance is a dark theme, and it's difficult to see the channel names

### Describe the solution you'd like

Ability to choose text colour for fader

### Describe alternatives you've considered

Haven't considered any alternatives

### Additional context

Feel free to say no if this is outside the scope of this project. I've tried changing text colour using external means, but it hasn't been successful, so I figured I might as well ask.

**Comment by wrodie** [comment]
That sounds like a fair question.  I've probably been a bit absolute with colours like that.  
I'll look into what I can do to make it respect the theme, or have an absolute colour choice.

**Comment by wrodie** [comment]
I've published a new version (v0.1.6), that removes the hard coding of this text colour.  It should now work properly with dark mode etc.
